### PR TITLE
[IVANCHUK] Unittest .travis.yml to ensure excludes match the matrix

### PR DESCRIPTION
**Pull request by miha-plesko**
Same as https://github.com/ManageIQ/manageiq-providers-nuage/pull/182, but for Redfish provider.

### CODE REVIEW

**Comment by himdel** [comment]
2 concerns:

* shouldn't this be a master PR with ivanchuk/yes ?
* https://github.com/ManageIQ/manageiq-ui-classic/pull/5885/files#r308168006

**Comment by miha-plesko** [comment]
@himdel since we've merged the other PR for Redfish we'll now have to do it like this with dedicated PR against ivanchuk, right? So I've addressed the second comment and pushed here.

**Comment by agrare** [comment]
@miha-plesko are you trying to apply the same fix to the ivanchuk branch?  If so @simaishi will just cherry-pick your commit to master back to the ivanchuk branch.  There is no need for a specific PR unless something is substantially different between the two.

**Comment by miha-plesko** [comment]
@agrare cherry-pick will fail because .travis.yml is different on ivanchuk. But yes, what I want to do is get this rspec to the ivanchuk. Problem is .travis.yml has been changed in the same commit.

**Comment by agrare** [comment]
Ah okay :+1:

**Comment by himdel** [comment]
Up to you, I'd still go with a master PR + backport, especially since this PR doesn't change `.travis.yml` at all.

**Comment by simaishi** [comment]
@miha-plesko Next time, feel free to still mark the master PR as `/yes`. I will resolve conflicts during backport if it's minor (like .travis.yml) 😄

**Comment by miha-plesko** [comment]
Okay, lets have it your way guys, I'm outnumbered :)

**Pull request closed without merging**
