### PR TITLE
Move parsing code from collector to parser

### PR DESCRIPTION
**Pull request by tadeboro**
As the commit title suggests, this commit moves the parsing functionality to the right place.

The change is not strictly aesthetic though, since moving this functionality into parser that is reused in targeted refresh allows us to write parsing parts only once.

@miq-bot assign @agrare

### CODE REVIEW

**Comment by tadeboro** [comment]
@miq-bot add_label wip

**Comment by agrare** [comment]
I like the direction this is going @tadeboro

**Comment by tadeboro** [comment]
@miq-bot remove_label wip

**Comment by tadeboro** [comment]
@miq-bot add_label wip

This depends on https://github.com/ManageIQ/manageiq-providers-redfish/pull/29

**Comment by tadeboro** [comment]
@miq-bot remove_label wip

**Pull request merged**
